// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dsess12gruppe13.domain;

import dsess12gruppe13.domain.Post;

privileged aspect Post_Roo_JavaBean {
    
    public String Post.getBody() {
        return this.body;
    }
    
    public void Post.setBody(String body) {
        this.body = body;
    }
    
}
