// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.ac.tuwien.dse.fairsurgeries.domain;

import at.ac.tuwien.dse.fairsurgeries.domain.AdminDataOnDemand;
import at.ac.tuwien.dse.fairsurgeries.domain.AdminIntegrationTest;
import at.ac.tuwien.dse.fairsurgeries.service.AdminService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect AdminIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AdminIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AdminIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private AdminDataOnDemand AdminIntegrationTest.dod;
    
    @Autowired
    AdminService AdminIntegrationTest.adminService;
    
    @Test
    public void AdminIntegrationTest.testCountAllAdmins() {
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        long count = adminService.countAllAdmins();
        Assert.assertTrue("Counter for 'Admin' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AdminIntegrationTest.testFindAdmin() {
        Admin obj = dod.getRandomAdmin();
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Admin' failed to provide an identifier", id);
        obj = adminService.findAdmin(id);
        Assert.assertNotNull("Find method for 'Admin' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Admin' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AdminIntegrationTest.testFindAllAdmins() {
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        long count = adminService.countAllAdmins();
        Assert.assertTrue("Too expensive to perform a find all test for 'Admin', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Admin> result = adminService.findAllAdmins();
        Assert.assertNotNull("Find all method for 'Admin' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Admin' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AdminIntegrationTest.testFindAdminEntries() {
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        long count = adminService.countAllAdmins();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Admin> result = adminService.findAdminEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Admin' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Admin' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AdminIntegrationTest.testSaveAdmin() {
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", dod.getRandomAdmin());
        Admin obj = dod.getNewTransientAdmin(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Admin' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Admin' identifier to be null", obj.getId());
        adminService.saveAdmin(obj);
        Assert.assertNotNull("Expected 'Admin' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AdminIntegrationTest.testDeleteAdmin() {
        Admin obj = dod.getRandomAdmin();
        Assert.assertNotNull("Data on demand for 'Admin' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Admin' failed to provide an identifier", id);
        obj = adminService.findAdmin(id);
        adminService.deleteAdmin(obj);
        Assert.assertNull("Failed to remove 'Admin' with identifier '" + id + "'", adminService.findAdmin(id));
    }
    
}
