// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.ac.tuwien.dse.fairsurgeries.domain;

import at.ac.tuwien.dse.fairsurgeries.domain.PatientDataOnDemand;
import at.ac.tuwien.dse.fairsurgeries.domain.PatientIntegrationTest;
import at.ac.tuwien.dse.fairsurgeries.service.PatientService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect PatientIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PatientIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PatientIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private PatientDataOnDemand PatientIntegrationTest.dod;
    
    @Autowired
    PatientService PatientIntegrationTest.patientService;
    
    @Test
    public void PatientIntegrationTest.testCountAllPatients() {
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", dod.getRandomPatient());
        long count = patientService.countAllPatients();
        Assert.assertTrue("Counter for 'Patient' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PatientIntegrationTest.testFindPatient() {
        Patient obj = dod.getRandomPatient();
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Patient' failed to provide an identifier", id);
        obj = patientService.findPatient(id);
        Assert.assertNotNull("Find method for 'Patient' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Patient' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PatientIntegrationTest.testFindAllPatients() {
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", dod.getRandomPatient());
        long count = patientService.countAllPatients();
        Assert.assertTrue("Too expensive to perform a find all test for 'Patient', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Patient> result = patientService.findAllPatients();
        Assert.assertNotNull("Find all method for 'Patient' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Patient' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PatientIntegrationTest.testFindPatientEntries() {
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", dod.getRandomPatient());
        long count = patientService.countAllPatients();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Patient> result = patientService.findPatientEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Patient' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Patient' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PatientIntegrationTest.testSavePatient() {
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", dod.getRandomPatient());
        Patient obj = dod.getNewTransientPatient(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Patient' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Patient' identifier to be null", obj.getId());
        patientService.savePatient(obj);
        Assert.assertNotNull("Expected 'Patient' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PatientIntegrationTest.testDeletePatient() {
        Patient obj = dod.getRandomPatient();
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Patient' failed to provide an identifier", id);
        obj = patientService.findPatient(id);
        patientService.deletePatient(obj);
        Assert.assertNull("Failed to remove 'Patient' with identifier '" + id + "'", patientService.findPatient(id));
    }
    
}
