// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.ac.tuwien.dse.fairsurgeries.domain;

import at.ac.tuwien.dse.fairsurgeries.domain.PublicPerson;
import at.ac.tuwien.dse.fairsurgeries.domain.PublicPersonDataOnDemand;
import at.ac.tuwien.dse.fairsurgeries.service.PublicPersonService;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PublicPersonDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PublicPersonDataOnDemand: @Component;
    
    private Random PublicPersonDataOnDemand.rnd = new SecureRandom();
    
    private List<PublicPerson> PublicPersonDataOnDemand.data;
    
    @Autowired
    PublicPersonService PublicPersonDataOnDemand.publicPersonService;
    
    public PublicPerson PublicPersonDataOnDemand.getNewTransientPublicPerson(int index) {
        PublicPerson obj = new PublicPerson();
        return obj;
    }
    
    public PublicPerson PublicPersonDataOnDemand.getSpecificPublicPerson(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PublicPerson obj = data.get(index);
        BigInteger id = obj.getId();
        return publicPersonService.findPublicPerson(id);
    }
    
    public PublicPerson PublicPersonDataOnDemand.getRandomPublicPerson() {
        init();
        PublicPerson obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return publicPersonService.findPublicPerson(id);
    }
    
    public boolean PublicPersonDataOnDemand.modifyPublicPerson(PublicPerson obj) {
        return false;
    }
    
    public void PublicPersonDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = publicPersonService.findPublicPersonEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PublicPerson' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PublicPerson>();
        for (int i = 0; i < 10; i++) {
            PublicPerson obj = getNewTransientPublicPerson(i);
            try {
                publicPersonService.savePublicPerson(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
