// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.ac.tuwien.dse.fairsurgeries.domain;

import at.ac.tuwien.dse.fairsurgeries.domain.HospitalDataOnDemand;
import at.ac.tuwien.dse.fairsurgeries.domain.HospitalIntegrationTest;
import at.ac.tuwien.dse.fairsurgeries.service.HospitalService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect HospitalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HospitalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HospitalIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private HospitalDataOnDemand HospitalIntegrationTest.dod;
    
    @Autowired
    HospitalService HospitalIntegrationTest.hospitalService;
    
    @Test
    public void HospitalIntegrationTest.testCountAllHospitals() {
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", dod.getRandomHospital());
        long count = hospitalService.countAllHospitals();
        Assert.assertTrue("Counter for 'Hospital' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HospitalIntegrationTest.testFindHospital() {
        Hospital obj = dod.getRandomHospital();
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hospital' failed to provide an identifier", id);
        obj = hospitalService.findHospital(id);
        Assert.assertNotNull("Find method for 'Hospital' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Hospital' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HospitalIntegrationTest.testFindAllHospitals() {
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", dod.getRandomHospital());
        long count = hospitalService.countAllHospitals();
        Assert.assertTrue("Too expensive to perform a find all test for 'Hospital', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Hospital> result = hospitalService.findAllHospitals();
        Assert.assertNotNull("Find all method for 'Hospital' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Hospital' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HospitalIntegrationTest.testFindHospitalEntries() {
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", dod.getRandomHospital());
        long count = hospitalService.countAllHospitals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Hospital> result = hospitalService.findHospitalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Hospital' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Hospital' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HospitalIntegrationTest.testSaveHospital() {
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", dod.getRandomHospital());
        Hospital obj = dod.getNewTransientHospital(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Hospital' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Hospital' identifier to be null", obj.getId());
        hospitalService.saveHospital(obj);
        Assert.assertNotNull("Expected 'Hospital' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HospitalIntegrationTest.testDeleteHospital() {
        Hospital obj = dod.getRandomHospital();
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hospital' failed to provide an identifier", id);
        obj = hospitalService.findHospital(id);
        hospitalService.deleteHospital(obj);
        Assert.assertNull("Failed to remove 'Hospital' with identifier '" + id + "'", hospitalService.findHospital(id));
    }
    
}
