// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.ac.tuwien.dse.fairsurgeries.domain;

import at.ac.tuwien.dse.fairsurgeries.domain.NotificationIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect NotificationIntegrationTest_Roo_Configurable {
    
    declare @type: NotificationIntegrationTest: @Configurable;
    
}
