// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.ac.tuwien.dse.fairsurgeries.domain;

import at.ac.tuwien.dse.fairsurgeries.domain.NotificationDataOnDemand;
import at.ac.tuwien.dse.fairsurgeries.domain.NotificationIntegrationTest;
import at.ac.tuwien.dse.fairsurgeries.service.NotificationService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect NotificationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NotificationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NotificationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private NotificationDataOnDemand NotificationIntegrationTest.dod;
    
    @Autowired
    NotificationService NotificationIntegrationTest.notificationService;
    
    @Test
    public void NotificationIntegrationTest.testCountAllNotifications() {
        Assert.assertNotNull("Data on demand for 'Notification' failed to initialize correctly", dod.getRandomNotification());
        long count = notificationService.countAllNotifications();
        Assert.assertTrue("Counter for 'Notification' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NotificationIntegrationTest.testFindNotification() {
        Notification obj = dod.getRandomNotification();
        Assert.assertNotNull("Data on demand for 'Notification' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notification' failed to provide an identifier", id);
        obj = notificationService.findNotification(id);
        Assert.assertNotNull("Find method for 'Notification' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Notification' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NotificationIntegrationTest.testFindAllNotifications() {
        Assert.assertNotNull("Data on demand for 'Notification' failed to initialize correctly", dod.getRandomNotification());
        long count = notificationService.countAllNotifications();
        Assert.assertTrue("Too expensive to perform a find all test for 'Notification', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Notification> result = notificationService.findAllNotifications();
        Assert.assertNotNull("Find all method for 'Notification' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Notification' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NotificationIntegrationTest.testFindNotificationEntries() {
        Assert.assertNotNull("Data on demand for 'Notification' failed to initialize correctly", dod.getRandomNotification());
        long count = notificationService.countAllNotifications();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Notification> result = notificationService.findNotificationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Notification' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Notification' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NotificationIntegrationTest.testSaveNotification() {
        Assert.assertNotNull("Data on demand for 'Notification' failed to initialize correctly", dod.getRandomNotification());
        Notification obj = dod.getNewTransientNotification(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Notification' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Notification' identifier to be null", obj.getId());
        notificationService.saveNotification(obj);
        Assert.assertNotNull("Expected 'Notification' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NotificationIntegrationTest.testDeleteNotification() {
        Notification obj = dod.getRandomNotification();
        Assert.assertNotNull("Data on demand for 'Notification' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notification' failed to provide an identifier", id);
        obj = notificationService.findNotification(id);
        notificationService.deleteNotification(obj);
        Assert.assertNull("Failed to remove 'Notification' with identifier '" + id + "'", notificationService.findNotification(id));
    }
    
}
