// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.ac.tuwien.dse.fairsurgeries.domain;

import at.ac.tuwien.dse.fairsurgeries.domain.PublicPersonDataOnDemand;
import at.ac.tuwien.dse.fairsurgeries.domain.PublicPersonIntegrationTest;
import at.ac.tuwien.dse.fairsurgeries.service.PublicPersonService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect PublicPersonIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PublicPersonIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PublicPersonIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private PublicPersonDataOnDemand PublicPersonIntegrationTest.dod;
    
    @Autowired
    PublicPersonService PublicPersonIntegrationTest.publicPersonService;
    
    @Test
    public void PublicPersonIntegrationTest.testCountAllPublicpeople() {
        Assert.assertNotNull("Data on demand for 'PublicPerson' failed to initialize correctly", dod.getRandomPublicPerson());
        long count = publicPersonService.countAllPublicpeople();
        Assert.assertTrue("Counter for 'PublicPerson' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PublicPersonIntegrationTest.testFindPublicPerson() {
        PublicPerson obj = dod.getRandomPublicPerson();
        Assert.assertNotNull("Data on demand for 'PublicPerson' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PublicPerson' failed to provide an identifier", id);
        obj = publicPersonService.findPublicPerson(id);
        Assert.assertNotNull("Find method for 'PublicPerson' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PublicPerson' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PublicPersonIntegrationTest.testFindAllPublicpeople() {
        Assert.assertNotNull("Data on demand for 'PublicPerson' failed to initialize correctly", dod.getRandomPublicPerson());
        long count = publicPersonService.countAllPublicpeople();
        Assert.assertTrue("Too expensive to perform a find all test for 'PublicPerson', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PublicPerson> result = publicPersonService.findAllPublicpeople();
        Assert.assertNotNull("Find all method for 'PublicPerson' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PublicPerson' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PublicPersonIntegrationTest.testFindPublicPersonEntries() {
        Assert.assertNotNull("Data on demand for 'PublicPerson' failed to initialize correctly", dod.getRandomPublicPerson());
        long count = publicPersonService.countAllPublicpeople();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PublicPerson> result = publicPersonService.findPublicPersonEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PublicPerson' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PublicPerson' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PublicPersonIntegrationTest.testSavePublicPerson() {
        Assert.assertNotNull("Data on demand for 'PublicPerson' failed to initialize correctly", dod.getRandomPublicPerson());
        PublicPerson obj = dod.getNewTransientPublicPerson(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PublicPerson' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PublicPerson' identifier to be null", obj.getId());
        publicPersonService.savePublicPerson(obj);
        Assert.assertNotNull("Expected 'PublicPerson' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PublicPersonIntegrationTest.testDeletePublicPerson() {
        PublicPerson obj = dod.getRandomPublicPerson();
        Assert.assertNotNull("Data on demand for 'PublicPerson' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PublicPerson' failed to provide an identifier", id);
        obj = publicPersonService.findPublicPerson(id);
        publicPersonService.deletePublicPerson(obj);
        Assert.assertNull("Failed to remove 'PublicPerson' with identifier '" + id + "'", publicPersonService.findPublicPerson(id));
    }
    
}
